import { useState } from 'react';
import DataTable, { TableColumn } from 'react-data-table-component';
import Badge from '../../ui/badge/Badge';
import { ProductDto } from '../../../app/models/product/product.model.ts';
import { useNavigate } from 'react-router'

interface ProductTableComponentProps {
  data: ProductDto[];
  loading: boolean;
  totalPages: number;
  currentPage: number;
  onPageChange: (page: number) => void;
  onSearch: (term: string) => void;
  totalCount: number;
  searchTerm: string;
}

export default function ProductTableComponent({ data }: ProductTableComponentProps) {
  const [selectedProducts, setSelectedProducts] = useState<ProductDto[]>([]);
  const navigate = useNavigate();

  const handleView = (product: ProductDto) => {
    navigate("/products/detail/" + product.id);
  };

  const handleSelectedRowsChange = (state: {
    allSelected: boolean;
    selectedCount: number;
    selectedRows: ProductDto[];
  }) => {
    setSelectedProducts(state.selectedRows);
    console.log('Selected Products:', state.selectedRows);
    console.log(selectedProducts)
  };

  const columns: TableColumn<ProductDto>[] = [
    {
      name: 'Id',
      selector: row => row.id,
      sortable: true,
      maxWidth: '5px'
    },
    {
      name: 'Mã hàng',
      selector: row => row.confirmProductCode,
      sortable: true,
    },
    {
      name: 'Mã nhà cung cấp',
      selector: row => row.supplierCode,
    },
    {
      name: 'Mã hàng nhà cung cấp',
      selector: row => row.confirmSupplierItemCode,
      sortable: true,
    },
    {
      name: 'Giá gốc',
      selector: row => row.productPrice?.toLocaleString() ?? '',
      sortable: true,
    },
    {
      name: 'Giá khuyến mãi',
      selector: row => row.discountedPrice?.toLocaleString() ?? '',
      sortable: true,
    },
    // {
    //   name: 'Đơn vị tính',
    //   selector: row => row.autoCalculatedUnit,
    // },
    // {
    //   name: 'Ghi chú đặc biệt',
    //   selector: row => row.productSpecialNote,
    // },
    // {
    //   name: 'Kích thước tự tạo',
    //   selector: row => row.autoGeneratedSize,
    // },
    // {
    //   name: 'Trọng lượng/đơn vị',
    //   selector: row => row.weightPerUnit,
    // },
    // {
    //   name: 'Trọng lượng/thùng',
    //   selector: row => row.weightPerBox,
    // },
    // {
    //   name: 'Số lượng/hộp',
    //   selector: row => row.quantityPerBox,
    // },
    // {
    //   name: 'Diện tích/đơn vị',
    //   selector: row => row.areaPerUnit,
    // },
    // {
    //   name: 'Diện tích/thùng',
    //   selector: row => row.areaPerBox,
    // },
    // {
    //   name: 'Hấp thụ nước',
    //   selector: row => row.waterAbsorption,
    // },
    // {
    //   name: 'Số mẫu',
    //   selector: row => row.patternQuantity,
    // },
    // {
    //   name: 'Mã mẫu gạch',
    //   selector: row => row.brickPatternShortName,
    // },
    // {
    //   name: 'Ngày giao dự kiến',
    //   selector: row => row.deliveryEstimatedDate,
    // },
    // {
    //   name: 'Quốc gia sản xuất',
    //   selector: row => row.originCountryName,
    // },
    {
      name: 'Kích thước thực tế',
      selector: row => row.actualSizeName,
    },
    // {
    //   name: 'Mẫu gạch',
    //   selector: row => row.brickPatternName,
    // },
    // {
    //   name: 'Màu sắc',
    //   selector: row => row.colorName,
    // },
    // {
    //   name: 'Bề mặt',
    //   selector: row => row.surfaceFeatureName,
    // },
    // {
    //   name: 'Chất liệu',
    //   selector: row => row.materialName,
    // },
    // {
    //   name: 'Xương gạch',
    //   selector: row => row.brickBodyName,
    // },
    // {
    //   name: 'Kho hàng',
    //   selector: row => row.storageName,
    // },
    // {
    //   name: 'Mức chống trượt',
    //   selector: row => row.antiSlipLevelName,
    // },
    // {
    //   name: 'Mã công ty',
    //   selector: row => row.companyCode,
    // },
    // {
    //   name: 'Mã xử lý',
    //   selector: row => row.productProcessingCode,
    // },
    // {
    //   name: 'Mô tả xử lý',
    //   selector: row => row.processingDescription,
    // },
    // {
    //   name: 'Phân loại giá',
    //   selector: row => row.priceDetermination,
    // },
    // {
    //   name: 'Ghi chú website',
    //   selector: row => row.noticeDataWebsite,
    // },
    // {
    //   name: 'Ngày tạo',
    //   selector: row => row.createdDate,
    // },
    // {
    //   name: 'Ngày cập nhật',
    //   selector: row => row.updatedAt,
    // },
    {
      name: 'Tình trạng Upload',
      selector: row => row.uploadWebsiteStatus,
      sortable: true,
      cell: row => (
        <Badge
          size="sm"
          color={
            row.uploadWebsiteStatus === 'Uploaded'
              ? 'success'
              : row.uploadWebsiteStatus === 'Pending'
                ? 'warning'
                : 'error'
          }
        >
          {row.uploadWebsiteStatus}
        </Badge>
      ),
    },
    {
      name: 'Hành động',
      cell: row => (
        <button
          onClick={() => handleView(row)}
          className="text-blue-600 hover:underline font-medium"
        >
          Xem
        </button>
      ),
      ignoreRowClick: true,
      allowOverflow: true,
      button: true,
    }
  ];

  return (
    <div className="rounded-xl overflow-hidden border border-gray-200 bg-white dark:border-white/[0.05] dark:bg-white/[0.03] p-4">
      <DataTable
        columns={columns}
        data={data}
        pagination
        responsive
        highlightOnHover
        striped
        selectableRows
        onSelectedRowsChange={handleSelectedRowsChange}
      />
    </div>
  );
}
